<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>AgroControl.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AgroControl.Application\AgroControl.Application.csproj" />
    <ProjectReference Include="..\AgroControl.Infrastructure\AgroControl.Infrastructure.csproj" />
  </ItemGroup>
</Project>
