<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\AgroControl.Application\AgroControl.Application.csproj" />
    <ProjectReference Include="..\AgroControl.Contracts\AgroControl.Contracts.csproj" />
    <ProjectReference Include="..\AgroControl.Infrastructure\AgroControl.Infrastructure.csproj" />
  </ItemGroup>
</Project>
